### ISSUE TITLE
deploy app on Render

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#304]
## Task Description
Based on the free-tier benefits we will enjoy from being on [Render](https://render.com) as compared to Heroku, the current decision is to host the app on the former.

## Technical Considerations
1. Create an account on [Render](https://render.com) using the official teamwork email. Depending on who picks this up, kindly contact the appropriate admins for this if necessary (@jakazzy etc :))
2. Deploy the app along with the necessary resources  (database and so on). Contact the aforementioned admins for the necessary environmental variables
3. Export the current data we have in our Heroku Postgres database 
4.  Import the exported data in the preceding step into the  Render Postgres database

**Comment by jakazzy** [comment]
Update:
Deployment of the application is completed on render.
`https://teamwork-t1z2.onrender.com/api/v1/health`

Copying data from heroku postgres to render postgres result in timeout. 
So though deplyment is successful, we do not have the production data on render. 
Also there's no admin user on render postgres currently. 

Ps. heroku postgres was changed to maintenance mode.

**Comment by jakazzy** [comment]
Also on the free plan these are what we get
**For the webservice**
1. The free plan allows 750 total hours of usage per month.
2. Effective March 1st, 2022, the free plan allows 400 total build hours per month for free services and static sites. After the build limit is exceeded, you will be charged a per-second prorated rate. Read more about build limits in [https://dashboard.render.com/billing#free-plan](https://render.com/docs/build-limits).

When we exceed the free usage, free services in the account are suspended until the 1st of every month. Kindly find more [here](https://render.com/docs/free)

**Also for the pstgresQL Database:**
we have access to the postgress database up till February 17, 2023 (90 days after account creation)
After which database service will be suspended until an upgrade is made from a free plan.

**Comment by jakazzy** [comment]
uploading the data is successful now. 
Tested with the admin user. we are yet to test the rest of the endpoints.

**Comment by jakazzy** [comment]
Some challenges that were encountered along the way:
Challenge 1. **User's relation cannot be found**
Web service  and postgreSQL were successfully created on render. 
The `DATABASE_URL` was updated in the env variable of the web service, to that of render postgres.
However when the login endpoint was tested by @Carl it resulted in an error `status 500, Internal server error`.
From the web service logs, it showed the `user relation does not exist.`

Solution:
From this, it was understood that the user's table had not been created. Hence the migration script had not yet run. 
To further confirm this, a  the postgres database was connected to with PostgreSQL client using the external database url on the dashboard.
![external_database_url](https://user-images.githubusercontent.com/22964028/202908931-65db28a6-e7d6-4d51-93c0-2eddec039f9e.png)

**Another error** However this resulted in another error. The error outputed was
```
SSL/TLS required
```
To fix this so as to be able to connect to the database using the connection string(external database url), this quey param 
needed to be added. The connection string became
```
<EXTERNAL_DATABASE_URL?ssl=true>
```
Viewing the database, it was confirmed that the migrations had not been created on the database on render.

To fix this the `build command` and the `start command` had to be updated to what's below
![start_and_build_commands](https://user-images.githubusercontent.com/22964028/202909367-129b2ea8-b19f-4e1c-b173-d41e996eee7d.png)

Ps.  
``` --ignore-scripts
``` was added so the ```npm run prepare``` which is in our package.json to setup husky will not run.

also ``` npm rebuild``` is added due to error encountered with bcrypt.  View the error that was encountered below
```Error: Cannot find module '/opt/render/project/src/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
```
From this stack overflow response, running [npm rebuild](https://stackoverflow.com/questions/34546272/cannot-find-module-bcrypt). Fixed it. 

Challenge 2.  **Connection timing out when importing production data into render.**
Following this [documentation by render](https://render.com/docs/migrate-from-heroku) it gave ample steps on how to migrate from heroku to render. Notable amongst it was how to copy the data from heroku to render.

After following the steps and downloading the data, uploading to render using the command

```
pg_restore --verbose  --no-acl --no-owner -d <EXTERNAL CONNECTION STRING> latest.dump
```
was resulting in connection timing out as observed in the error below
```
pg_restore: error: connection to server at "<HOST_NAME>" (35.227.164.209), port 5433 failed: Connection timed out
Is the server running on that host and accepting TCP/IP connections?
```
It was later realised that the error was as a result of the port number being used. This was therefore changed to
```
pg_restore --verbose  --no-acl --no-owner -d <EXTERNAL CONNECTION STRING>:5432 latest.dump
```
The data was now successfully imported into render postgreSQL

**Comment by jakazzy** [comment]
The endpoints have been tested now.
