### ISSUE TITLE
deploy app on Railway

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#330]
## Task Description
Based on the free-tier benefits we will enjoy from being on [Railway](https://railway.app) as compared to Heroku, the current decision is to host the app on the former.

## Technical Considerations
1. Create an account on [Railway](https://railway.app) using the official teamwork email. Depending on who picks this up, kindly contact the appropriate admins for this if necessary (@jakazzy etc :))
2. Deploy the app along with the necessary resources  (database and so on). Contact the aforementioned admins for the necessary environmental variables
3. Export the current data we have in our Heroku Postgres database 
4.  Import the exported data in the preceding step into the  Railway Postgres database

**Comment by jakazzy** [comment]
I looked into deploying the app on Railway. It looked like a cool alternative.
 The starter plan was 500 execution hours which is different from render 750 hours. when we run out of execution hours in a month, the deployment will be suspended and we will need to redeploy.
 
 Compared to render, the database does not get suspended after 90days.
 https://docs.railway.app/reference/plans

**Comment by jakazzy** [comment]
Deploying on railway is quite smoother than render.
1. Everytime an environment variable changes, railyway runs the build and redeploy.
2. Railway provides GUI for postgress. So once can see and edit the data visually in production.
3. The database does not get suspended after 90 days
4. Also we are able to provide invite access to other members to edit config.
Plus railway provides more services for free compared to render(eg. deploy cron )

The only challenge was connecting https://github.com/tbf-challenge/teamwork-be repository. 
Since Railway could read all my public repositories, i could not connect teamwork. 
We may need to setup continuous deployment

**Comment by jakazzy** [comment]
Application is still running on Render, Heroku and now Railway

Heroku: https://team-worker.herokuapp.com/api/v1
Render: https://teamwork-t1z2.onrender.com/api/v1
Railway: https://teamwork.up.railway.app/api/v1
